[package]
name = "{{project_name}}-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "{{project_name}}"
path = "src/main.rs"

[dependencies]
{{project_name}}-core = { path = "../core" }
